---
pool:
  name: "Azure Pipelines"
  vmImage: ubuntu-latest

trigger:
  - develop

stages:  
  - stage: printing_disk_Space
    displayName: printing_disk_Space 

    jobs:
      - job: print
        displayName: printing_freedisk

        steps: 
          - script: sudo df -h