---
pool:
  name: "Azure Pipelines"
  vmImage: ubuntu-latest

trigger:
  - develop

stages:  
  - stage: updating_packages
    displayName: updating_packages

    jobs:
      - job: print
        displayName: updating_packages

        steps: 
          - script: sudo apt update
          